# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c8ca9403cd74c7792f4ea03b93f24ee55211cb20f4623b647a4e383f6d30b7870e7b25bab52791fe22d043b446588931134827b67af6fbdeaf1dff6d282352aa

test:
  secret_key_base: 1f6ce6f55033ce099e70ffe43df5679ae60d108ce79c942b1860795e351af2bd16f1bbf952d3fadd082588790ffc29f3c219465036ac25da5b8d48d8dc3eb335

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
